FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /build

COPY common/pom.xml ./common/pom.xml
COPY common/src ./common/src
RUN mvn -f ./common/pom.xml -X dependency:go-offline clean install -DskipTests

COPY producer/pom.xml ./producer/pom.xml
COPY producer/src ./producer/src
RUN mvn -f ./producer/pom.xml clean package -DskipTests

FROM openjdk:18-jdk
WORKDIR /app

COPY --from=build /build/producer/target/producer*.jar /app/producer.jar

CMD ["java", "-jar", "producer.jar"]