services:
  producer:
    build:
      context: ../..
      dockerfile: Dockerfile-producer
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
    networks:
      - demo

networks:
  demo:
    name: demo